### ISSUE TITLE
feature request: Toggle action

### ISSUE THREAD

**Issue by voldikss** [Kraust/floater.nvim#1]
Nice plugin, also nice **plugin name**

I have done some progress that may be useful to this feature.

https://github.com/voldikss/dotfiles/blob/0e1893e1894952012c007ba52cf423b47dac289d/vim/vimrc#L779-L810

**Comment by Kraust** [comment]
I added the command `:FloaterToggle` - does this do what you want it to do?

(I didn't see that you had already done this, decided to do it on my own)
